[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:extractor]
command=uvicorn main:app --host 0.0.0.0 --port 8081
directory=/app/extractor
priority=10
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:synthesis]
command=node dist/server.js
directory=/app/synthesis
priority=20
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
